import React, { useEffect, useMemo, useState } from "react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { getStarredQuestionIds } from "@/lib/starred";
import { ALL_COURSE_TYPES, filterQuestionsByCourse, getCourseTypes, sortCourseTypes, type CourseSort } from "@/lib/courseTypes";
import { ArrowRight, BookOpenCheck, CheckCircle2, ChevronLeft, CircleAlert, Flame, History, Home as HomeIcon, LogIn, RotateCcw, Settings, ShieldCheck, Sparkles, Star, Target, XCircle } from "lucide-react";

type Section = "home" | "quiz" | "wrong" | "stats" | "admin" | "settings";
type Mode = "practice" | "mock" | "wrong" | "starred";

type Answer = { questionId: string; sequenceNo: number; selectedOption: "A" | "B" | "C" | "D"; correctOption: "A" | "B" | "C" | "D"; isCorrect: boolean; markedReviewError?: string };

const optionLabels = { A: "A", B: "B", C: "C", D: "D" } as const;

export default function Home() {
  const { user, loading, logout } = useAuth();
  const { data, isLoading } = trpc.quiz.bootstrap.useQuery();
  const requestedView = new URLSearchParams(window.location.search).get("view");
  const requestedMode = new URLSearchParams(window.location.search).get("mode");
  const [section, setSection] = useState<Section>(() => ["quiz", "wrong", "stats", "admin", "settings"].includes(requestedView ?? "") ? requestedView as Section : "home");
  const [mode, setMode] = useState<Mode>(() => ["practice", "mock", "wrong", "starred"].includes(requestedMode ?? "") ? requestedMode as Mode : "practice");
  const [count, setCount] = useState(5);
  const [courseType, setCourseType] = useState(ALL_COURSE_TYPES);
  const [courseSort, setCourseSort] = useState<CourseSort>("default");
  const [starTagFilter, setStarTagFilter] = useState("全部");
  const [activeQuestions, setActiveQuestions] = useState<any[]>([]);
  const [cursor, setCursor] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [selected, setSelected] = useState<keyof typeof optionLabels | null>(null);
  const [finished, setFinished] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [wrongFilter, setWrongFilter] = useState("待複習");
  const [fontScale, setFontScale] = useState(() => Number(localStorage.getItem("sep4-font-scale") || "1"));
  const [density, setDensity] = useState<"comfortable" | "compact">(() => localStorage.getItem("sep4-density") === "compact" ? "compact" : "comfortable");
  useEffect(() => { localStorage.setItem("sep4-font-scale", String(fontScale)); }, [fontScale]);
  useEffect(() => { localStorage.setItem("sep4-density", density); }, [density]);
  const questions = data?.questions ?? [];
  const current = activeQuestions[cursor];
  const history = trpc.attempts.history.useQuery(undefined, { enabled: Boolean(user) });
  const stats = trpc.attempts.stats.useQuery(undefined, { enabled: Boolean(user) });
  const courseProgress = trpc.attempts.courseProgress.useQuery(undefined, { enabled: Boolean(user) });
  const learningGoal = trpc.attempts.learningGoal.useQuery(undefined, { enabled: Boolean(user) });
  const wrong = trpc.wrongQuestions.list.useQuery(undefined, { enabled: Boolean(user) });
  const starred = trpc.starredQuestions.list.useQuery(undefined, { enabled: Boolean(user) });
  const starredIds = useMemo(() => new Set((starred.data ?? []).map((row: any) => row.questionId)), [starred.data]);
  const starTags = useMemo(() => Array.from(new Set((starred.data ?? []).map((row: any) => row.tag).filter(Boolean))).sort() as string[], [starred.data]);
  const filteredStarredIds = useMemo(() => getStarredQuestionIds(starred.data ?? [], starTagFilter), [starred.data, starTagFilter]);
  const starredStats = trpc.starredQuestions.stats.useQuery(undefined, { enabled: Boolean(user) });
  const courseTypes = useMemo(() => getCourseTypes(questions), [questions]);
  const sortedCourseTypes = useMemo(() => sortCourseTypes(courseTypes, courseProgress.data, courseSort), [courseTypes, courseProgress.data, courseSort]);
  const filtered = useMemo(() => {
    const modePool = mode === "starred" ? questions.filter((q: any) => filteredStarredIds.has(q.id)) : questions;
    return filterQuestionsByCourse(modePool, courseType);
  }, [questions, courseType, mode, filteredStarredIds]);
  const complete = trpc.attempts.complete.useMutation({ onSuccess: value => { setResult(value); setFinished(true); history.refetch(); wrong.refetch(); starredStats.refetch(); courseProgress.refetch(); } });
  const toggleStar = trpc.starredQuestions.toggle.useMutation({ onSuccess: () => starred.refetch() });
  const updateStarTag = trpc.starredQuestions.updateTag.useMutation({ onSuccess: () => starred.refetch() });
  const updateStarReminder = trpc.starredQuestions.updateReminder.useMutation({ onSuccess: () => { starred.refetch(); starredStats.refetch(); } });
  const updateLearningGoal = trpc.attempts.updateLearningGoal.useMutation({ onSuccess: () => learningGoal.refetch() });

  const startQuiz = () => {
    const pool = [...filtered];
    const selectedQuestions = pool.sort(() => Math.random() - 0.5).slice(0, Math.min(count, pool.length));
    setMode(mode); setActiveQuestions(selectedQuestions); setCursor(0); setAnswers([]); setSelected(null); setFinished(false); setResult(null); setSection("quiz");
    localStorage.setItem("sep4-active-attempt", JSON.stringify({ mode, count, courseType, starTagFilter, questionIds: selectedQuestions.map((q: any) => q.id), answers: [] }));
  };

  const submitAnswer = (option: keyof typeof optionLabels) => {
    if (!current || selected) return;
    setSelected(option);
    const answer: Answer = { questionId: current.id, sequenceNo: cursor, selectedOption: option, correctOption: current.correctOption, isCorrect: option === current.correctOption };
    setAnswers(prev => [...prev, answer]);
  };

  const markAndContinue = (mark?: string) => {
    if (!current || !selected) return;
    const nextAnswers = answers.map(a => a.questionId === current.id ? { ...a, markedReviewError: mark } : a);
    setAnswers(nextAnswers);
    if (cursor + 1 >= activeQuestions.length) {
      if (!user) { setFinished(true); setResult({ score: Math.round(nextAnswers.filter(a => a.isCorrect).length / activeQuestions.length * 100), correctCount: nextAnswers.filter(a => a.isCorrect).length, wrongCount: nextAnswers.filter(a => !a.isCorrect).length, passed80: false }); return; }
      complete.mutate({ mode, questionCount: activeQuestions.length, answers: nextAnswers });
    } else { setCursor(cursor + 1); setSelected(null); localStorage.setItem("sep4-active-attempt", JSON.stringify({ mode, count, courseType, starTagFilter, questionIds: activeQuestions.map((q: any) => q.id), answers: nextAnswers })); }
  };

  const nav = (next: Section) => { setSection(next); if (next !== "quiz") { setFinished(false); setActiveQuestions([]); } };

  if (isLoading || loading) return <div className="app-shell"><div className="loading-card">正在準備你的題庫…</div></div>;

  return <div className={`app-shell reading-scale-${fontScale === 1.15 ? "large" : fontScale === 0.9 ? "small" : "normal"} density-${density}`}>
    <header className="topbar"><div><div className="eyebrow">9/4 應試準備室</div><h1>專注，從一題開始。</h1></div><div className="top-actions"><Button variant="ghost" className="settings-button" aria-label="閱讀設定" onClick={() => setSection("settings")}><Settings size={17}/><span>閱讀設定</span></Button>{user ? <Button variant="ghost" className="user-pill" onClick={() => logout()}>{user.name || "已登入"} · 登出</Button> : <Button variant="outline" className="login-button" onClick={() => startLogin()}><LogIn size={16}/> Manus OAuth 登入</Button>}</div></header>
    <main className="content">
      {section === "home" && <Dashboard onStart={() => { setSection("quiz"); }} onStartCourse={(nextCourseType: string) => { setCourseType(nextCourseType); setMode("practice"); setSection("quiz"); }} onStartStarred={() => { if (!user) return startLogin(); setMode("starred"); setSection("quiz"); }} data={data} user={user} starStats={starredStats.data} courseProgress={courseProgress.data} learningGoal={learningGoal.data} onAdmin={() => setSection("admin")} />}
      {section === "quiz" && (!activeQuestions.length ? <QuizSetup courseType={courseType} setCourseType={setCourseType} courseTypes={sortedCourseTypes} courseProgress={courseProgress.data} courseSort={courseSort} setCourseSort={setCourseSort} learningGoal={learningGoal.data} onUpdateGoal={(targetCompletion: number) => updateLearningGoal.mutate({ targetCompletion })} goalPending={updateLearningGoal.isPending} isLoggedIn={Boolean(user)} mode={mode} setMode={setMode} count={count} setCount={setCount} onStart={startQuiz} available={filtered.length} starredCount={starredIds.size} starTags={starTags} starTagFilter={starTagFilter} setStarTagFilter={setStarTagFilter} /> : <QuizRunner current={current} cursor={cursor} total={activeQuestions.length} selected={selected} mode={mode} finished={finished} result={result} isStarred={starredIds.has(current?.id)} starPending={toggleStar.isPending} onToggleStar={() => user ? toggleStar.mutate({ questionId: current.id }) : startLogin()} onAnswer={submitAnswer} onMark={markAndContinue} onBack={() => { setActiveQuestions([]); setSection("home"); }} />)}
      {section === "wrong" && <WrongPanel rows={wrong.data ?? []} starRows={starred.data ?? []} questions={questions} filter={wrongFilter} setFilter={setWrongFilter} onSaveTag={(questionId: string, tag: string | null) => updateStarTag.mutate({ questionId, tag })} onSaveReminder={(questionId: string, reminderDate: string | null) => updateStarReminder.mutate({ questionId, reminderDate })} onStart={(q: any) => { const full = questions.find((item: any) => item.id === q.questionId); if (!full) return; setMode("wrong"); setActiveQuestions([full]); setCursor(0); setAnswers([]); setSelected(null); setFinished(false); setSection("quiz"); }} />}
      {section === "stats" && <StatsPanel attempts={history.data ?? []} stats={stats.data} starredStats={starredStats.data} />}
      {section === "admin" && <AdminPanel isAdmin={user?.role === "admin"} />}
      {section === "settings" && <ReadingSettings fontScale={fontScale} setFontScale={setFontScale} density={density} setDensity={setDensity} onBack={() => setSection("home")} />}
    </main>
    <nav className="bottom-nav">{[["home", HomeIcon, "首頁"],["quiz", BookOpenCheck, "測驗"],["wrong", RotateCcw, "錯題"],["stats", History, "統計"]].map(([key, Icon, label]) => <button key={key as string} className={section === key ? "active" : ""} onClick={() => nav(key as Section)}><Icon size={19}/><span>{label as string}</span></button>)}</nav>
  </div>;
}

function Dashboard({ onStart, onStartCourse, onStartStarred, data, user, starStats, courseProgress, learningGoal, onAdmin }: any) { const reminderText = !user ? "登入後建立個人星號複習" : starStats?.dueCount ? `有 ${starStats.dueCount} 題已到提醒日` : starStats?.upcomingCount ? `7 日內有 ${starStats.upcomingCount} 題待複習` : "目前沒有到期提醒"; return <div className="dashboard-grid"><section className="hero-card"><div className="hero-copy"><Badge className="soft-badge"><Target size={14}/> 9/4 甄試倒數</Badge><h2>把不確定，練成穩定。</h2><p>以官方題庫為核心，讓每一次作答都更接近 80 分目標。</p><Button className="primary-cta" onClick={onStart}>開始測驗 <ArrowRight size={17}/></Button></div><div className="hero-orbit"><span>80</span><small>目標分</small></div></section><section className="metric-row"><Metric icon={<Flame/>} label="目前錯題" value={user ? "同步後查看" : "登入後同步"}/><Metric icon={<CheckCircle2/>} label="已熟悉" value="—"/><Metric icon={<ShieldCheck/>} label="題庫狀態" value={`${data?.qa?.enabled ?? 0} 題可練`}/></section><HomeCourseSummary user={user} courseProgress={courseProgress} learningGoal={learningGoal} onStartCourse={onStartCourse}/><section className="home-star-summary"><div><div className="eyebrow">星號複習</div><strong>{starStats?.completionRate ?? 0}% 已複習</strong><p>{starStats?.reviewedCount ?? 0} / {starStats?.total ?? 0} 題 · {reminderText}</p></div><Button variant="outline" onClick={onStartStarred} disabled={Boolean(user && !starStats?.total)}><Star size={16}/> 星號隨機測驗</Button></section><section className="quick-grid"><QuickCard title="快速練習" desc="5 題即時回饋" onClick={onStart}/><QuickCard title="20 題模擬考" desc="完成後揭曉分數" onClick={onStart}/><QuickCard title="考前衝刺" desc="優先複習弱點" onClick={onStart}/></section>{user?.role === "admin" && <button className="admin-link" onClick={onAdmin}><ShieldCheck size={16}/> 開啟題庫管理後台</button>}</div> }
function HomeCourseSummary({ user, courseProgress, learningGoal, onStartCourse }: any) { if (!user) return <section className="home-course-summary home-course-summary-guest"><div><div className="eyebrow">課程學習摘要</div><strong>登入後掌握各科進度</strong><p>答對率、完成度與目標提醒會依你的作答紀錄同步。</p></div><Button variant="outline" onClick={() => startLogin()}><LogIn size={16}/> 登入查看</Button></section>; if (!courseProgress) return <section className="home-course-summary"><span className="muted">正在載入你的課程學習摘要…</span></section>; const target = learningGoal?.targetCompletion ?? 60; return <section className="home-course-summary"><div className="home-course-heading"><div><div className="eyebrow">課程學習摘要</div><strong>掌握每一科的下一步</strong></div><Badge className="course-goal-badge">目標 {target}%</Badge></div><div className="home-course-grid">{courseProgress.map((course: any) => { const remaining = Math.max(target - course.completion, 0); return <article className="home-course-row" key={course.source}><div className="home-course-row-heading"><strong>{course.label}</strong><span>{course.accuracy === null ? "尚未作答" : `答對率 ${course.accuracy}%`}</span></div><div className="home-course-track"><i style={{ width: `${course.completion}%` }}/></div><div className="home-course-row-footer"><span>{course.completion}% 完成 {remaining ? `· 距目標 ${remaining}%` : "· 已達目標"}</span><Button variant="outline" size="sm" onClick={() => onStartCourse(course.source)}>練這科 <ArrowRight size={14}/></Button></div></article>; })}</div></section>; }
function Metric({ icon, label, value }: any) { return <Card className="metric-card"><CardContent><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></CardContent></Card> }
function QuickCard({ title, desc, onClick }: any) { return <button className="quick-card" onClick={onClick}><span>{title}</span><small>{desc}</small><ArrowRight size={16}/></button> }
function CourseProgressHint({ courseType, courseTypes, courseProgress, learningGoal, onUpdateGoal, goalPending, isLoggedIn }: any) {
  const visibleTypes = courseType === ALL_COURSE_TYPES ? courseTypes : courseTypes.filter((type: any) => type.id === courseType);
  if (!isLoggedIn) return <div className="course-progress-hint muted"><strong>登入後查看個人課程進度</strong><span>系統會記錄各課程的答對率與完成度。</span></div>;
  if (!courseProgress) return <div className="course-progress-hint muted">正在載入你的課程進度…</div>;
  const target = learningGoal?.targetCompletion ?? 60;
  const averageCompletion = visibleTypes.length ? Math.round(visibleTypes.reduce((sum: number, type: any) => sum + (courseProgress.find((item: any) => item.source === type.id)?.completion ?? 0), 0) / visibleTypes.length) : 0;
  const remaining = Math.max(target - averageCompletion, 0);
  return <section className="course-progress-hint" aria-label="課程進度">
    <div className="course-progress-heading"><strong>課程進度</strong><span>完成度以已作答的不重複題目計算</span></div>
    <div className={`course-goal-reminder ${remaining ? "needs-action" : "on-track"}`}><Sparkles size={16}/><span>{remaining ? `距離 ${target}% 完成度目標還有 ${remaining}%，完成下一回合就更接近。` : `已達成 ${target}% 完成度目標，保持這個節奏。`}</span></div>
    <label className="goal-picker">設定目標完成度<select aria-label="設定目標完成度" value={target} disabled={goalPending} onChange={event => onUpdateGoal(Number(event.target.value))}>{[25, 40, 60, 80, 100].map(value => <option value={value} key={value}>{value}%</option>)}</select></label>
    <div className="course-progress-list">{visibleTypes.map((type: any) => {
      const progress = courseProgress.find((item: any) => item.source === type.id);
      const completion = progress?.completion ?? 0;
      const accuracy = progress?.accuracy;
      return <div className="course-progress-row" key={type.id}>
        <div className="course-progress-copy"><strong>{type.label}</strong><span>{progress ? `${progress.answered} 次作答 · ${completion}% 完成` : "尚未開始"}</span></div>
        <div className="course-progress-track" aria-label={`${type.label} 完成度 ${completion}%`}><i style={{ width: `${completion}%` }}/></div>
        <span className="course-accuracy">{accuracy === null || accuracy === undefined ? "尚未作答" : `答對率 ${accuracy}%`}</span>
      </div>;
    })}</div>
  </section>;
}
function QuizSetup({ courseType, setCourseType, courseTypes, courseProgress, courseSort, setCourseSort, learningGoal, onUpdateGoal, goalPending, isLoggedIn, mode, setMode, count, setCount, onStart, available, starredCount, starTags, starTagFilter, setStarTagFilter }: any) { const starredMode = mode === "starred"; return <div className="setup-wrap"><button className="back-link" onClick={() => window.history.back()}><ChevronLeft size={16}/> 回首頁</button><div className="section-heading"><div className="eyebrow">測驗設定</div><h2>今天想怎麼練？</h2><p>選擇課程類型、題數與範圍，系統會避免同場重複題目。</p></div><Card className="setup-card"><CardHeader><CardTitle>測驗模式</CardTitle></CardHeader><CardContent><Tabs value={mode} onValueChange={v => setMode(v as Mode)}><TabsList className="mode-tabs mode-tabs-four"><TabsTrigger value="practice">練習模式</TabsTrigger><TabsTrigger value="mock">模擬考</TabsTrigger><TabsTrigger value="wrong">錯題重刷</TabsTrigger><TabsTrigger value="starred">星號隨機</TabsTrigger></TabsList><TabsContent value="practice"><p className="muted">每題作答後立即顯示正解與解析。</p></TabsContent><TabsContent value="mock"><p className="muted">20 題完成前不公布單題對錯，完成後顯示是否達標。</p></TabsContent><TabsContent value="wrong"><p className="muted">集中處理待複習題目，連續答對兩次即標為已熟悉。</p></TabsContent><TabsContent value="starred"><p className="muted">僅從你標記星號的題目隨機抽題，也可以進一步選擇指定標籤與課程類型。</p></TabsContent></Tabs><label>課程排序<select aria-label="課程排序" value={courseSort} onChange={event => setCourseSort(event.target.value as CourseSort)}><option value="default">預設排序</option><option value="accuracy-asc">答對率最低優先</option><option value="completion-asc">完成度最低優先</option></select></label><label>課程類型<select aria-label="課程類型" value={courseType} onChange={e => setCourseType(e.target.value)}><option value={ALL_COURSE_TYPES}>全部課程</option>{courseTypes.map((type: { id: string; label: string }) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><CourseProgressHint courseType={courseType} courseTypes={courseTypes} courseProgress={courseProgress} learningGoal={learningGoal} onUpdateGoal={onUpdateGoal} goalPending={goalPending} isLoggedIn={isLoggedIn}/><label>題數<select value={count} onChange={e => setCount(Number(e.target.value))}><option value={5}>5 題快速練習</option><option value={10}>10 題一般練習</option><option value={20}>20 題模擬考</option></select></label>{starredMode && <label>星號標籤<select value={starTagFilter} onChange={e => setStarTagFilter(e.target.value)}><option>全部</option>{starTags.map((tag: string) => <option key={tag}>{tag}</option>)}</select></label>}<Button className="primary-cta wide" onClick={onStart} disabled={!available}>開始這一回合 <ArrowRight size={17}/></Button><p className="availability">{starredMode ? `目前有 ${available} / ${starredCount} 題星號題目符合篩選` : `目前課程範圍有 ${available} 題可用`}</p></CardContent></Card></div> }
function QuizRunner({ current, cursor, total, selected, mode, finished, result, isStarred, starPending, onToggleStar, onAnswer, onMark, onBack }: any) { const mock = mode === "mock"; return <div className="runner-wrap"><button className="back-link" onClick={onBack}><ChevronLeft size={16}/> 結束本回合</button>{finished ? <Card className="result-card"><div className="result-kicker">本回合完成</div><h2>{result?.score ?? 0}<small> 分</small></h2><p>{result?.passed80 ? "已達到 80 分目標。" : "還差一點，下一回合會更穩。"}</p><div className="result-stats"><span>答對 <b>{result?.correctCount ?? 0}</b></span><span>答錯 <b>{result?.wrongCount ?? 0}</b></span></div><Button className="primary-cta" onClick={onBack}>返回首頁</Button></Card> : <><div className="progress-line"><span>第 {cursor + 1} / {total} 題</span><div><i style={{ width: `${((cursor + 1) / total) * 100}%` }}/></div></div><Card className="question-card"><div className="question-meta"><div className="question-badges"><Badge variant="outline">{current.source === "AI" ? "AI 工具應用" : "電腦硬體"}</Badge>{current.needsReview && <Badge className="review-badge"><CircleAlert size={13}/> 待審</Badge>}</div><Button variant={isStarred ? "default" : "outline"} size="sm" className={`star-button ${isStarred ? "starred" : ""}`} aria-pressed={isStarred} disabled={starPending} onClick={onToggleStar}><Star size={16} fill={isStarred ? "currentColor" : "none"}/>{isStarred ? "已標記" : "標記星號"}</Button></div><h2>{current.text}</h2><div className="answers">{Object.entries(current.options).map(([key, value]) => <button key={key} className={`answer-button ${selected ? (key === current.correctOption ? "correct" : key === selected ? "wrong" : "muted") : ""}`} onClick={() => onAnswer(key as any)}><span className="answer-letter">{key}</span><span>{value as string}</span>{selected && key === current.correctOption && <CheckCircle2 size={18}/>} {selected && key === selected && key !== current.correctOption && <XCircle size={18}/>}</button>)}</div>{selected && !mock && <div className={`feedback ${selected === current.correctOption ? "good" : "bad"}`}><strong>{selected === current.correctOption ? "答對了" : "再看一次"}</strong><p>正解：{current.correctOption}。{current.explanation || "官方資料未提供解析。"}</p></div>}{selected && mock && <div className="mock-hint">答案已暫存，完成整份模擬考後揭曉。</div>}{selected && !mock && selected !== current.correctOption && <div className="mark-actions"><span>這題答錯的原因？</span><Button variant="outline" onClick={() => onMark("真的不會")}>真的不會</Button><Button variant="outline" onClick={() => onMark("題目看反")}>題目看反</Button></div>}{selected && (selected === current.correctOption || mock) && <Button className="primary-cta wide next-button" onClick={() => onMark()}>{cursor + 1 === total ? "查看結果" : "下一題"} <ArrowRight size={17}/></Button>}</Card></>}</div> }
export function StarMetaEditor({ row, onSaveTag, onSaveReminder }: any) { const [tag, setTag] = useState(row.tag || ""); const [reminderDate, setReminderDate] = useState(row.reminderDate || ""); useEffect(() => { setTag(row.tag || ""); setReminderDate(row.reminderDate || ""); }, [row.tag, row.reminderDate]); return <div className="star-meta-editor"><div className="tag-editor"><input aria-label={`標籤 ${row.questionId}`} value={tag} maxLength={64} placeholder="例如：考前必看" onChange={event => setTag(event.target.value)} /><Button variant="outline" size="sm" onClick={() => onSaveTag(row.questionId, tag.trim() || null)}>儲存標籤</Button></div><div className="reminder-editor"><label>提醒日期<input aria-label={`提醒日期 ${row.questionId}`} type="date" value={reminderDate} onChange={event => setReminderDate(event.target.value)} /></label><Button variant="outline" size="sm" onClick={() => onSaveReminder(row.questionId, reminderDate || null)}>儲存提醒</Button></div></div> }
function WrongPanel({ rows, starRows, questions, filter, setFilter, onStart, onSaveTag, onSaveReminder }: any) { const visible = rows.filter((r: any) => filter === "全部" || r.status === filter); const today = new Date().toISOString().slice(0, 10); const starred = starRows.map((row: any) => ({ ...row, question: questions.find((question: any) => question.id === row.questionId) })).filter((row: any) => row.question); return <div className="panel-wrap"><div className="section-heading"><div className="eyebrow">錯題與複習</div><h2>把不熟悉的，練成穩定。</h2><p>星號題目會獨立保存，不會與答錯紀錄混在一起。</p></div><section className="starred-section"><div className="starred-heading"><div><Star size={17} fill="currentColor"/><strong>星號複習</strong></div><Badge>{starred.length} 題</Badge></div>{starred.length ? <div className="starred-list">{starred.map((row: any) => <Card className="starred-row" key={row.id}><CardContent><div><h3>{row.question.questionId}</h3><p>{row.question.text.slice(0, 80)}{row.question.text.length > 80 ? "…" : ""}</p>{row.reminderDate && <Badge className={row.reminderDate <= today ? "reminder-badge due" : "reminder-badge"}>{row.reminderDate <= today ? "今日／已到期" : `提醒 ${row.reminderDate}`}</Badge>}<StarMetaEditor row={row} onSaveTag={onSaveTag} onSaveReminder={onSaveReminder}/></div><Button variant="outline" onClick={() => onStart({ questionId: row.questionId })}>重刷</Button></CardContent></Card>)}</div> : <p className="starred-empty">在答題時按下「標記星號」，就能把不熟悉題目集中在這裡。</p>}</section><div className="filter-pills">{["待複習", "已熟悉", "全部"].map(f => <button className={filter === f ? "selected" : ""} onClick={() => setFilter(f)} key={f}>{f}</button>)}</div>{visible.length ? visible.map((r: any) => <Card className="wrong-row" key={r.id}><CardContent><div><Badge>{r.status}</Badge><h3>{r.questionId}</h3><p>錯誤 {r.wrongCount} 次 · 連續答對 {r.consecutiveCorrect} 次</p></div><Button variant="outline" onClick={() => onStart({ questionId: r.questionId })}>重刷</Button></CardContent></Card>) : <div className="empty-state"><RotateCcw size={28}/><h3>目前沒有符合條件的錯題</h3><p>完成幾回練習後，這裡會自動整理你的複習清單。</p></div>}</div> }
function StatsPanel({ attempts, stats, starredStats }: any) { const overall = stats?.totalAnswered ? Math.round(stats.totalCorrect / stats.totalAnswered * 100) : 0; const lastReviewed = starredStats?.lastReviewedAt ? new Date(starredStats.lastReviewedAt).toLocaleDateString("zh-TW", { month: "numeric", day: "numeric" }) : "尚未複習"; const reminderText = starredStats?.dueCount ? `${starredStats.dueCount} 題今日／已到期` : starredStats?.upcomingCount ? `${starredStats.upcomingCount} 題將在 7 日內到期` : "目前沒有待處理提醒"; return <div className="panel-wrap"><div className="section-heading"><div className="eyebrow">統計</div><h2>看見自己的進步。</h2><p>歷次測驗紀錄會在完成後自動同步。</p></div><div className="metric-row"><Metric icon={<BookOpenCheck/>} label="總答題數" value={stats?.totalAnswered ?? "—"}/><Metric icon={<CheckCircle2/>} label="總正確率" value={stats ? `${overall}%` : "—"}/><Metric icon={<History/>} label="歷史回合" value={attempts.length}/></div><Card className="starred-stats-card"><CardContent><div><div className="eyebrow">星號複習進度</div><h3>{starredStats?.completionRate ?? 0}% 已完成</h3><p>{starredStats?.reviewedCount ?? 0} / {starredStats?.total ?? 0} 題至少複習一次</p></div><div className="last-reviewed"><span>最近複習</span><strong>{lastReviewed}</strong><small>{reminderText}</small></div></CardContent></Card><div className="admin-list">{Object.entries(stats?.bySubject ?? {}).map(([subject, value]: any) => <Card className="history-row" key={subject}><CardContent><span>{subject}</span><strong>{value.accuracy}%</strong><small>{value.correct}/{value.answered} 題答對</small></CardContent></Card>)}</div>{attempts.length ? attempts.map((a: any) => <Card className="history-row" key={a.id}><CardContent><span>{a.mode === "mock" ? "模擬考" : a.mode === "starred" ? "星號隨機測驗" : "練習"}</span><strong>{a.score} 分</strong><small>{a.correctCount}/{a.questionCount} 題答對</small></CardContent></Card>) : <div className="empty-state"><History size={28}/><h3>尚未有測驗紀錄</h3><p>完成第一回測驗後，這裡會顯示你的歷史成績。</p></div>}</div> }
function ReadingSettings({ fontScale, setFontScale, density, setDensity, onBack }: any) { return <div className="panel-wrap settings-panel"><button className="back-link" onClick={onBack}><ChevronLeft size={16}/> 回首頁</button><div className="section-heading"><div className="eyebrow">閱讀設定</div><h2>調整成你的節奏。</h2><p>設定會儲存在此裝置，下次開啟 App 會自動還原。</p></div><Card className="setup-card"><CardHeader><CardTitle>字級大小</CardTitle></CardHeader><CardContent><div className="setting-options" role="group" aria-label="字級大小"><Button variant={fontScale === 0.9 ? "default" : "outline"} onClick={() => setFontScale(0.9)}>較小</Button><Button variant={fontScale === 1 ? "default" : "outline"} onClick={() => setFontScale(1)}>標準</Button><Button variant={fontScale === 1.15 ? "default" : "outline"} onClick={() => setFontScale(1.15)}>較大</Button></div><p className="setting-preview">目前題目閱讀預覽：以官方題庫為核心，讓每一次作答都更接近目標。</p></CardContent></Card><Card className="setup-card"><CardHeader><CardTitle>排版密度</CardTitle></CardHeader><CardContent><div className="setting-options" role="group" aria-label="排版密度"><Button variant={density === "comfortable" ? "default" : "outline"} onClick={() => setDensity("comfortable")}>舒適</Button><Button variant={density === "compact" ? "default" : "outline"} onClick={() => setDensity("compact")}>緊湊</Button></div><p className="setting-preview">舒適模式增加卡片間距與行距；緊湊模式讓一個畫面容納更多資訊。</p></CardContent></Card></div> }

function AdminPanel({ isAdmin }: { isAdmin: boolean }) { const [reviewOnly, setReviewOnly] = useState(true); const [editing, setEditing] = useState<any>(null); const [explanation, setExplanation] = useState(""); const [correctOption, setCorrectOption] = useState<any>("A"); const query = trpc.quiz.adminList.useQuery({ needsReviewOnly: reviewOnly }, { enabled: isAdmin }); const save = trpc.quiz.adminUpdate.useMutation({ onSuccess: () => { setEditing(null); query.refetch(); } }); if (!isAdmin) return <div className="empty-state"><ShieldCheck size={30}/><h3>需要 admin 權限</h3><p>此區域不對一般使用者開放。</p></div>; return <div className="panel-wrap"><div className="section-heading"><div className="eyebrow">Admin only</div><h2>題庫管理</h2><p>優先處理待審題目；官方答案仍以 PDF Source of Truth 為準。</p></div>{editing && <Card className="setup-card"><CardHeader><CardTitle>編輯 {editing.id}</CardTitle></CardHeader><CardContent><label>正確答案<select value={correctOption} onChange={e => setCorrectOption(e.target.value)}>{["A","B","C","D"].map(o => <option key={o}>{o}</option>)}</select></label><label>解析<textarea value={explanation} onChange={e => setExplanation(e.target.value)} rows={5}/></label><div className="mark-actions"><Button className="primary-cta" onClick={() => save.mutate({ questionId: editing.id, explanation, correctOption })}>儲存更新</Button><Button variant="outline" onClick={() => setEditing(null)}>取消</Button></div></CardContent></Card>}<div className="admin-toolbar"><Button variant={reviewOnly ? "default" : "outline"} onClick={() => setReviewOnly(true)}>只看待審</Button><Button variant={!reviewOnly ? "default" : "outline"} onClick={() => setReviewOnly(false)}>全部題目</Button><Badge>{query.data?.length ?? 0} 題</Badge></div><div className="admin-list">{query.data?.slice(0, 80).map((q: any) => <Card key={q.id} className="admin-row"><CardContent><div><Badge className={q.needsReview ? "review-badge" : ""}>{q.needsReview ? "待審" : "已匯入"}</Badge><h3>{q.id} · {q.text.slice(0, 80)}{q.text.length > 80 ? "…" : ""}</h3><p>正解：{q.correctOption} · {q.section}</p></div><Button variant="outline" size="sm" onClick={() => { setEditing(q); setExplanation(q.explanation || ""); setCorrectOption(q.correctOption); }}>編輯</Button></CardContent></Card>)}</div></div> }
